# boink/cdbg.tpl.pyx.pxi
# Copyright (C) 2018 Camille Scott
# All rights reserved.
#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
#
# WARNING: this file is automatically generated; do not modify it!
# The source template is: cdbg.tpl.pyx

cdef class cDBG_Base:

    SAVE_FORMATS = ['graphml', 'edgelist',
                    'gfa1', 'gfa2', 'fasta', 'gml']

    def __cinit__(self, *args, **kwargs):
        pass


cdef cDBGFormat convert_format(str file_format) except *:
    if file_format in cDBG_Base.SAVE_FORMATS:
        if file_format == 'graphml':
            return cDBGFormat.GRAPHML
        elif file_format == 'fasta':
            return cDBGFormat.FASTA
        elif file_format == 'gfa1':
            return cDBGFormat.GFA1
        else:
            raise NotImplementedError("Support for {0} not yet "
                                      "implemented".format(file_format))
    else:
        formats = ', '.join(cDBG_Base.SAVE_FORMATS)
        raise ValueError("{0} not a valid save format. "
                         "Format must be one of: {1}".format(file_format,
                                                             formats))

cdef class cDBG__BitStorage__DefaultShifter(cDBG_Base):

    @staticmethod
    cdef cDBG__BitStorage__DefaultShifter _wrap(_cDBG[_dBG[_BitStorage,_DefaultShifter]] * ptr):
        cdef cDBG__BitStorage__DefaultShifter cdbg = cDBG__BitStorage__DefaultShifter()
        cdbg._this = ptr
        cdbg.Notifier = EventNotifier._wrap(<_EventNotifier*>cdbg._this);
        return cdbg
    '''
    def unodes(self):
        cdef _cDBG[_dBG[_BitStorage,_DefaultShifter]].unode_iter_t it = \
                deref(self._this).unodes_begin()
        cdef _UnitigNode * unode
        while(it != deref(self._this).unodes_end()):
            unode = deref(it).second.get()
            yield UnitigNodeView._wrap(unode)
            princ(it)


    def dnodes(self):
        cdef _cDBG[_dBG[_BitStorage,_DefaultShifter]].dnode_iter_t it = \
                deref(self._this).dnodes_begin()
        cdef _DecisionNode * dnode
        while(it != deref(self._this).dnodes_end()):
            dnode = deref(it).second.get()
            yield DecisionNodeView._wrap(dnode)
            princ(it)
    '''

    def query_unode_hash(self, hash_t h):
        cdef _UnitigNode * _node = deref(self._this).query_unode_tag(h)
        if _node != NULL:
            return UnitigNodeView._wrap(_node)
        else:
            return None

    def query_unode_id(self, id_t node_id):
        cdef _UnitigNode * _node = \
            deref(self._this).query_unode_id(node_id)
        if _node != NULL:
            return UnitigNodeView._wrap(_node)
        else:
            return None

    def query_unode_end(self, hash_t h):
        cdef _UnitigNode * _node = \
            deref(self._this).query_unode_end(h)
        if _node != NULL:
            return UnitigNodeView._wrap(_node)
        else:
            return None
    
    def query_dnode(self, hash_t h):
        cdef _DecisionNode * _node = \
            deref(self._this).query_dnode(h)
        if _node != NULL:
            return DecisionNodeView._wrap(_node)
        else:
            return None

    def has_dnode(self, hash_t h):
        return deref(self._this).has_dnode(h)

    def query_dnodes(self, str sequence):
        pass

    @property
    def n_updates(self):
        return deref(self._this).n_updates()

    @property
    def n_unodes(self):
        return deref(self._this).n_unitig_nodes()

    @property
    def n_dnodes(self):
        return deref(self._this).n_decision_nodes()

    @property
    def n_tags(self):
        return deref(self._this).n_tags()

    @property
    def n_unitig_ends(self):
        return deref(self._this).n_unitig_ends()

    def validate(self, str filename):
        deref(self._this).validate(_bstring(filename))

    def save(self, str filename, str file_format):
        if file_format is None:
            return
        else:
            deref(self._this).write(_bstring(filename),
                                    convert_format(file_format))

cdef class cDBG__ByteStorage__DefaultShifter(cDBG_Base):

    @staticmethod
    cdef cDBG__ByteStorage__DefaultShifter _wrap(_cDBG[_dBG[_ByteStorage,_DefaultShifter]] * ptr):
        cdef cDBG__ByteStorage__DefaultShifter cdbg = cDBG__ByteStorage__DefaultShifter()
        cdbg._this = ptr
        cdbg.Notifier = EventNotifier._wrap(<_EventNotifier*>cdbg._this);
        return cdbg
    '''
    def unodes(self):
        cdef _cDBG[_dBG[_ByteStorage,_DefaultShifter]].unode_iter_t it = \
                deref(self._this).unodes_begin()
        cdef _UnitigNode * unode
        while(it != deref(self._this).unodes_end()):
            unode = deref(it).second.get()
            yield UnitigNodeView._wrap(unode)
            princ(it)


    def dnodes(self):
        cdef _cDBG[_dBG[_ByteStorage,_DefaultShifter]].dnode_iter_t it = \
                deref(self._this).dnodes_begin()
        cdef _DecisionNode * dnode
        while(it != deref(self._this).dnodes_end()):
            dnode = deref(it).second.get()
            yield DecisionNodeView._wrap(dnode)
            princ(it)
    '''

    def query_unode_hash(self, hash_t h):
        cdef _UnitigNode * _node = deref(self._this).query_unode_tag(h)
        if _node != NULL:
            return UnitigNodeView._wrap(_node)
        else:
            return None

    def query_unode_id(self, id_t node_id):
        cdef _UnitigNode * _node = \
            deref(self._this).query_unode_id(node_id)
        if _node != NULL:
            return UnitigNodeView._wrap(_node)
        else:
            return None

    def query_unode_end(self, hash_t h):
        cdef _UnitigNode * _node = \
            deref(self._this).query_unode_end(h)
        if _node != NULL:
            return UnitigNodeView._wrap(_node)
        else:
            return None
    
    def query_dnode(self, hash_t h):
        cdef _DecisionNode * _node = \
            deref(self._this).query_dnode(h)
        if _node != NULL:
            return DecisionNodeView._wrap(_node)
        else:
            return None

    def has_dnode(self, hash_t h):
        return deref(self._this).has_dnode(h)

    def query_dnodes(self, str sequence):
        pass

    @property
    def n_updates(self):
        return deref(self._this).n_updates()

    @property
    def n_unodes(self):
        return deref(self._this).n_unitig_nodes()

    @property
    def n_dnodes(self):
        return deref(self._this).n_decision_nodes()

    @property
    def n_tags(self):
        return deref(self._this).n_tags()

    @property
    def n_unitig_ends(self):
        return deref(self._this).n_unitig_ends()

    def validate(self, str filename):
        deref(self._this).validate(_bstring(filename))

    def save(self, str filename, str file_format):
        if file_format is None:
            return
        else:
            deref(self._this).write(_bstring(filename),
                                    convert_format(file_format))

cdef class cDBG__NibbleStorage__DefaultShifter(cDBG_Base):

    @staticmethod
    cdef cDBG__NibbleStorage__DefaultShifter _wrap(_cDBG[_dBG[_NibbleStorage,_DefaultShifter]] * ptr):
        cdef cDBG__NibbleStorage__DefaultShifter cdbg = cDBG__NibbleStorage__DefaultShifter()
        cdbg._this = ptr
        cdbg.Notifier = EventNotifier._wrap(<_EventNotifier*>cdbg._this);
        return cdbg
    '''
    def unodes(self):
        cdef _cDBG[_dBG[_NibbleStorage,_DefaultShifter]].unode_iter_t it = \
                deref(self._this).unodes_begin()
        cdef _UnitigNode * unode
        while(it != deref(self._this).unodes_end()):
            unode = deref(it).second.get()
            yield UnitigNodeView._wrap(unode)
            princ(it)


    def dnodes(self):
        cdef _cDBG[_dBG[_NibbleStorage,_DefaultShifter]].dnode_iter_t it = \
                deref(self._this).dnodes_begin()
        cdef _DecisionNode * dnode
        while(it != deref(self._this).dnodes_end()):
            dnode = deref(it).second.get()
            yield DecisionNodeView._wrap(dnode)
            princ(it)
    '''

    def query_unode_hash(self, hash_t h):
        cdef _UnitigNode * _node = deref(self._this).query_unode_tag(h)
        if _node != NULL:
            return UnitigNodeView._wrap(_node)
        else:
            return None

    def query_unode_id(self, id_t node_id):
        cdef _UnitigNode * _node = \
            deref(self._this).query_unode_id(node_id)
        if _node != NULL:
            return UnitigNodeView._wrap(_node)
        else:
            return None

    def query_unode_end(self, hash_t h):
        cdef _UnitigNode * _node = \
            deref(self._this).query_unode_end(h)
        if _node != NULL:
            return UnitigNodeView._wrap(_node)
        else:
            return None
    
    def query_dnode(self, hash_t h):
        cdef _DecisionNode * _node = \
            deref(self._this).query_dnode(h)
        if _node != NULL:
            return DecisionNodeView._wrap(_node)
        else:
            return None

    def has_dnode(self, hash_t h):
        return deref(self._this).has_dnode(h)

    def query_dnodes(self, str sequence):
        pass

    @property
    def n_updates(self):
        return deref(self._this).n_updates()

    @property
    def n_unodes(self):
        return deref(self._this).n_unitig_nodes()

    @property
    def n_dnodes(self):
        return deref(self._this).n_decision_nodes()

    @property
    def n_tags(self):
        return deref(self._this).n_tags()

    @property
    def n_unitig_ends(self):
        return deref(self._this).n_unitig_ends()

    def validate(self, str filename):
        deref(self._this).validate(_bstring(filename))

    def save(self, str filename, str file_format):
        if file_format is None:
            return
        else:
            deref(self._this).write(_bstring(filename),
                                    convert_format(file_format))

cdef class cDBG__SparseppSetStorage__DefaultShifter(cDBG_Base):

    @staticmethod
    cdef cDBG__SparseppSetStorage__DefaultShifter _wrap(_cDBG[_dBG[_SparseppSetStorage,_DefaultShifter]] * ptr):
        cdef cDBG__SparseppSetStorage__DefaultShifter cdbg = cDBG__SparseppSetStorage__DefaultShifter()
        cdbg._this = ptr
        cdbg.Notifier = EventNotifier._wrap(<_EventNotifier*>cdbg._this);
        return cdbg
    '''
    def unodes(self):
        cdef _cDBG[_dBG[_SparseppSetStorage,_DefaultShifter]].unode_iter_t it = \
                deref(self._this).unodes_begin()
        cdef _UnitigNode * unode
        while(it != deref(self._this).unodes_end()):
            unode = deref(it).second.get()
            yield UnitigNodeView._wrap(unode)
            princ(it)


    def dnodes(self):
        cdef _cDBG[_dBG[_SparseppSetStorage,_DefaultShifter]].dnode_iter_t it = \
                deref(self._this).dnodes_begin()
        cdef _DecisionNode * dnode
        while(it != deref(self._this).dnodes_end()):
            dnode = deref(it).second.get()
            yield DecisionNodeView._wrap(dnode)
            princ(it)
    '''

    def query_unode_hash(self, hash_t h):
        cdef _UnitigNode * _node = deref(self._this).query_unode_tag(h)
        if _node != NULL:
            return UnitigNodeView._wrap(_node)
        else:
            return None

    def query_unode_id(self, id_t node_id):
        cdef _UnitigNode * _node = \
            deref(self._this).query_unode_id(node_id)
        if _node != NULL:
            return UnitigNodeView._wrap(_node)
        else:
            return None

    def query_unode_end(self, hash_t h):
        cdef _UnitigNode * _node = \
            deref(self._this).query_unode_end(h)
        if _node != NULL:
            return UnitigNodeView._wrap(_node)
        else:
            return None
    
    def query_dnode(self, hash_t h):
        cdef _DecisionNode * _node = \
            deref(self._this).query_dnode(h)
        if _node != NULL:
            return DecisionNodeView._wrap(_node)
        else:
            return None

    def has_dnode(self, hash_t h):
        return deref(self._this).has_dnode(h)

    def query_dnodes(self, str sequence):
        pass

    @property
    def n_updates(self):
        return deref(self._this).n_updates()

    @property
    def n_unodes(self):
        return deref(self._this).n_unitig_nodes()

    @property
    def n_dnodes(self):
        return deref(self._this).n_decision_nodes()

    @property
    def n_tags(self):
        return deref(self._this).n_tags()

    @property
    def n_unitig_ends(self):
        return deref(self._this).n_unitig_ends()

    def validate(self, str filename):
        deref(self._this).validate(_bstring(filename))

    def save(self, str filename, str file_format):
        if file_format is None:
            return
        else:
            deref(self._this).write(_bstring(filename),
                                    convert_format(file_format))


def get_cdbg_type(str storage='_BitStorage',
                  str shifter='_DefaultShifter'):
    if storage == "_BitStorage" and \
       shifter == "_DefaultShifter":
        return cDBG__BitStorage__DefaultShifter
    if storage == "_ByteStorage" and \
       shifter == "_DefaultShifter":
        return cDBG__ByteStorage__DefaultShifter
    if storage == "_NibbleStorage" and \
       shifter == "_DefaultShifter":
        return cDBG__NibbleStorage__DefaultShifter
    if storage == "_SparseppSetStorage" and \
       shifter == "_DefaultShifter":
        return cDBG__SparseppSetStorage__DefaultShifter
    raise TypeError("Invalid Storage or Shifter type: ({0},{1})".format(storage, shifter))


