# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

matrix:
  include:
    - os: osx
      compiler: clang

    - os: linux
      dist: xenial
      compiler: clang

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-5
            - g++-5-multilib
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - COMPILERS="CC=gcc-5 && CXX=g++-5"

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-6
            - g++-6-multilib
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - COMPILERS="CC=gcc-6 && CXX=g++-6"

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-7
            - g++-7-multilib
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - COMPILERS="CC=gcc-7 && CXX=g++-7"

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-8
            - g++-8-multilib
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - COMPILERS="CC=gcc-8 && CXX=g++-8"

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - mingw-w64
      env:
        - COMPILERS="CC=x86_64-w64-mingw32-gcc-posix && CXX=x86_64-w64-mingw32-g++-posix"

env:
  global:
    - CFLAGS="-O3 -g -Wall -Wextra -Werror -pedantic -Wno-long-long -Wno-missing-braces"
    - CXXFLAGS="-O3 -g -Wall -Wextra -Werror -pedantic -Wno-long-long -Wno-missing-braces"

before_install:
  # Overwrite default CC and CXX
  - eval "${COMPILERS}"

install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]
    then
        sudo apt-get install -y make cmake cppcheck valgrind g++-multilib
    fi

script:
  - |
    if [ "$CXX" = "x86_64-w64-mingw32-g++-posix" ]
    then
        # 1) Test MinGW/GCC compilation
        mkdir build
        cd build
        cmake .. -DCMAKE_SYSTEM_NAME=Windows \
                 -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
                 -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
        make -j4 VERBOSE=1

    elif [ "${TRAVIS_OS_NAME}" = "linux" ]
    then
        # 1) Static code analysis
        cppcheck . --error-exitcode=1 \
                   --quiet \
                   --force \
                   -itest/test2.c

        # 2) Run test suite
        mkdir build
        cd build
        cmake ..
        make -j4 VERBOSE=1
        ctest

        # 3) Runtime memory analysis
        cd test
        valgrind --error-exitcode=1 ./test1 30000

        # 4) Run test suite (32-bit)
        cd ../..
        rm -rf build
        mkdir build
        cd build
        cmake .. -DCMAKE_C_FLAGS="$CFLAGS -m32" \
                 -DCMAKE_CXX_FLAGS="$CXXFLAGS -m32"
        make -j4 VERBOSE=1
        ctest

    elif [ "${TRAVIS_OS_NAME}" = "osx" ]
    then
        # 1) Run test suite
        mkdir build
        cd build
        cmake ..
        make -j4 VERBOSE=1
        ctest
    fi
