#!/usr/bin/env python

import argparse
import sys

from boink.args import (build_dBG_args, add_pairing_args,
                        add_save_cDBG_args)
from boink.dbg import make_dBG
from boink.compactor import make_streaming_compactor
from boink.parsing import grouper
from boink.processors import make_streaming_compactor_processor
from boink.reporters import (make_streaming_compactor_reporter,
                             make_cdbgwriter_reporter,
                             cDBGHistoryReporter)



def parse_args():
    parser = build_dBG_args()
    add_pairing_args(parser)
    add_save_cDBG_args(parser)
    parser.add_argument('-o', dest='output_filename', default='/dev/stdout')
    parser.add_argument('-i', dest='inputs', nargs='+', default=['/dev/stdin'])

    args = parser.parse_args()
    return args


def main():
    args = parse_args()

    graph = make_dBG(args.ksize,
                     args.max_tablesize,
                     args.n_tables,
                     storage='_' + args.storage_type)
    compactor = make_streaming_compactor(graph)
    processor = make_streaming_compactor_processor(compactor,
                                                   args.save_stats_interval)
    reporter = make_streaming_compactor_reporter(args.save_cdbg_stats,
                                                 compactor)
    processor.Notifier.register_listener(reporter)

    writers = []
    if args.save_cdbg_format:
        for cdbg_format in args.save_cdbg_format:
            writer = make_cdbgwriter_reporter(args.save_cdbg_prefix + '.' + cdbg_format,
                                              cdbg_format,
                                              compactor.cdbg)
            processor.Notifier.register_listener(writer)
            writers.append(writer)

    if args.save_cdbg_history:
        print("Saving cDBG history DAG to", args.cdbg_history_filename)
        history = cDBGHistoryReporter(args.cdbg_history_filename)
        compactor.cdbg.Notifier.register_listener(history)


    if args.pairing_mode == 'split':
        _samples = grouper(2, args.inputs)
    else:
        _samples = args.inputs

    for sample in _samples:
        if args.pairing_mode == 'split':
            processor.process(*sample)
        else:
            processor.process(sample)

    if args.save_dbg:
        graph.save(args.savegraph)


if __name__ == '__main__':
    main()
