sudo: false
language: cpp
python:
  - "3.7"
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - python3
    - python3-dev
install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo apt-get install python3 python3-dev
  - sudo apt-get install -y python3-setuptools
  - sudo apt-get install python3-pip
before_install:
  - git submodule update --init --recursive
script:
  - make -f Makefile run_tests -j1
  - ./run_tests
  - cd python
  - python3 setup.py install --user --prefix=
notifications:
    slack: jhu-genomics:BbHYSks7DhOolq80IYf6m9oe#libsketch
    rooms:
      - jhu-genomics:BbHYSks7DhOolq80IYf6m9oe#libsketch
