name: Tests

on:
  push:
    branches: [latest, master, main]
  pull_request:
    branches: [latest, master, main]
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        py: [3.6, 3.7, 3.8]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: cache conda
        uses: actions/cache@v1
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment_dev.yml') }}

      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.py }}
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          activate-environment: goetia-dev
          environment-file: environment_dev.yml
          auto-activate-base: false
          use-only-tar-bz2: true
      
      - name: build
        run: |
          make install

      - name: 'tests: dbg'
        run: |
          pytest -v --benchmark-disable tests/test_dbg.py

      - name: 'tests: cdbg'
        run: |
          pytest -v --benchmark-disable tests/test_cdbg.py

      - name: 'tests: filters'
        run: |
          pytest -v --benchmark-disable tests/test_filters.py

      - name: 'tests: hashing'
        run: |
          pytest -v --benchmark-disable tests/test_hashing.py

      - name: 'tests: metrics'
        run: |
          pytest -v --benchmark-disable tests/test_metrics.py

      - name: 'tests: minimizers'
        run: |
          pytest -v --benchmark-disable tests/test_minimizers.py

      - name: 'tests: parsing'
        run: |
          pytest -v --benchmark-disable tests/test_parsing.py

      - name: 'tests: processors'
        run: |
          pytest -v --benchmark-disable tests/test_processors.py

      - name: 'tests: saturation'
        run: |
          pytest -v --benchmark-disable tests/test_saturation.py

      - name: 'tests: signatures'
        run: |
          pytest -v --benchmark-disable tests/test_signatures.py

      - name: 'tests: solid compactor'
        run: |
          pytest -v --benchmark-disable tests/test_solid_compactor.py

      - name: 'tests: traversal'
        run: |
          pytest -v --benchmark-disable tests/test_traversal.py

      - name: 'tests: ukhs'
        run: |
          pytest -v --benchmark-disable tests/test_ukhs.py
